<?php

/**
 * PluginfpPaymentCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginfpPaymentCart extends BasefpPaymentCart
{
  
  /**
   * Product item
   *
   * @var Doctrine_Record
   */
  protected $productItem;

	/**
   * Return product object
   *
   * @return Doctrine_Record
   */
  public function getProduct()
  {
    if (empty($this->productItem)) {
      $this->productItem = Doctrine::getTable($this->getObjectClassName())->find($this->getObjectId());
    }
    return $this->productItem;
  }
  
  /**
   * (non-PHPdoc)
   * @see BasefpPaymentCart::getObjectClassName()
   */
  public function getObjectClassName()
  {
    $tables = sfConfig::get('fp_payment_cart_object_classes_names');
    if (1 < count($tables)) {
      return parent::getObjectClassName();
    } else {
      return array_pop($tables); 
    }
  }
}