all:
  context_class_name: fpPaymentCartContext
  customer_model_name: <?php echo sfConfig::get('fp_payment_customer_model_name', 'sfGuardUser') ?> 
  customer_callback:
    function: 'fpPaymentContext::getInstance'
    parameters: []
    subFunctions: ['getCustomer']
  holders:
    decorator: 'fpPaymentCartHolder'
    authenticated:
      class: 'fpPaymentCartHolderDb'
    not_authenticated:
      session_ns: 'fpPaymentCart'
      class: 'fpPaymentCartHolderSession'
  login_strict_mode: false  # true => he have to be login, false => the user haven't to be login
  object_model_name: <?php echo sfConfig::get('fp_payment_object_classe_name', 'Product') ?> # name of product table
  object_partial: 'fpPaymentCart/product'
  css: '/fpPaymentCartPlugin/css/cart.css'
  js: '/fpPaymentCartPlugin/js/cart.js'
  js_overlay: '/fpPaymentCartPlugin/js/jquery.overlay.min.js'
  images_path: '/fpPaymentCartPlugin/images/'
  images:
    new:      'add_48x48.png'
    add:      'add_48x48.png'
    remove:   'remove_48x48.png'
    delete:   'delete_16x16.gif'
  labels:
    new:      'Add'
    add:      ' + Add'
    remove:   ' - Remove'
    delete:   'Remove item'
