all:
  context_class_name: fpPaymentCartContext
  customer_model_name: <?php echo sfConfig::get('fp_payment_customer_model_name', 'sfGuardUser') ?> 
  customer_callback:
    function: 'fpPaymentContext::getInstance'
    parameters: []
    subFunctions: ['getCustomer']
  holders:
    decorator: 'fpPaymentCartHolder'
    authenticated:
      class: 'fpPaymentCartHolderDb'
    not_authenticated:
      session_ns: 'fpPaymentCart'
      class: 'fpPaymentCartHolderSession'
  login_strict_mode: false  # true => he have to be login, false => the user haven't to be login
  routes:
    checkout: '@fpPaymentPlugin_checkout'
#    add:      '@showCart'
#    delete:   ''
  object_model_name: <?php echo sfConfig::get('fp_payment_object_classe_name', 'Product') ?> # name of product table

  css:         '/fpPaymentCartPlugin/css/cart.css'
  images_path: '/fpPaymentCartPlugin/images/'
  images:
    new:      'add_48.png'
    add:      'add_48.png'
    show:     'show_48.png'
    delete:   'delete_48.png'
    loader:   'ajax-loader.gif'
  labels:
    new:      'Add'
    add:      ' + Add'
    show:     'Show'
    delete:   ' - Remove'
    loader:   'Current record'
