all:
  user_model: sfGuardUser
  callback_user:
    function: 'fpPaymentContext::getInstance'
    parameters: []
    subFunctions: ['getUser']
  cartable_extra_fields: # it aren't dynamyc fields
#    photo:
#      name: photo
#      alias: null
#      type: string
#      length: null
#      options:
#        notnull: true
    description:
      name: description
      alias: null
      type: string
      length: null
      options: 
        notnull: true
  holders:
    decorator: 'fpPaymentCartHolder'
    authenticated:
      class: 'fpPaymentCartHolderDb'
    not_authenticated:
      session_ns: 'fpPaymentCart'
      class: 'fpPaymentCartHolderSession'
  login_strict_mode: false # true => he have to be login, false => the user haven't to be logged
  routes:
    checkout: '@fpPaymentPlugin_checkout_payment_methods'
#    add:      '@showCart'
#    delete:   ''
  object_model_name: 'Product' # name of product table

  css:         '/fpPaymentCartPlugin/css/cart.css'
  images_path: '/fpPaymentCartPlugin/images/'
  images:
    new:      add_48.png
    add:      add_48.png
    show:     show_48.png
    delete:   delete_48.png
    loader:   ajax-loader.gif
  labels:
    new:      Add
    add:      + Add
    show:     Show
    delete:   Delete
    loader:   Current record