fpPaymentCart:
  actAs:
    Timestampable: ~
  columns:
    customer_id: {type: integer, notnull: true}
    object_id: {type: integer, notnull: true}
    quantity: {type: integer, notnull: true}
  relations:
    Customer:
      class: <?php echo sfConfig::get('fp_payment_cart_customer_model_name', 'sfGuardUser') ?> 
      local: customer_id
      onDelete: CASCADE
    Product:
      class: <?php echo sfConfig::get('fp_payment_cart_object_model_name', 'Product') ?> 
      local: object_id
      onDelete: CASCADE