 
fpPaymentCart:
  actAs:
    Timestampable: ~
  columns:
    customer_id: {type: integer, notnull: true}
    object_id: {type: integer, notnull: true}
    quantity: {type: integer, notnull: true}
  relations:
    Customer:
      class: sfGuardUser
      local: customer_id
      onDelete: CASCADE
    Product:
      class: <?php sfConfig::get('fp_payment_cart_object_classes_names', 'product') ?>
      local: object_id
      onDelete: CASCADE